name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g floss electron http-server
      - run: npm install
      - run: npm run serve
      - run: npm run test:build
      - uses: coactions/setup-xvfb@v1
        with:
          run: floss --path ./dist/test.js
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-image-artifacts
          path: ./tests/artifacts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-image-current
          path: ./tests/current