name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g floss electron http-server
      - run: npm install
      - run: npm run serve
      - run: sudo ufw allow 8080/tcp
      - run: sleep 3
      - run: npm run check
      - run: npm run test:build
      - uses: GabrielBB/xvfb-action@v1.6
        with:
          run: floss --path ./dist/test.js