name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo $(pwd)
      - run: echo $NODE_ENV
      - run: npm install -g floss electron
      - run: npm install --production=false
      - run: npm run test:build
      - run: bash ./file_check.sh
      - run: floss -h
      - run: npm run test:run