name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install electron
        run: npm install -g floss electron http-server
      - name: Install npm dependencies
        run: npm install
      - name: Start server
        run: npm run serve
      - name: Build tests
        run: npm run test:build
      - name: Run headless test
        uses: coactions/setup-xvfb@v1
        with:
          run: DEBUG=1  floss --path ./dist/test.js
      - name: Upload images with artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-image-artifacts
          path: ./tests/artifacts
      - name: Upload generated images
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-image-current
          path: ./tests/current